# This is a config for E2B sandbox template.
# You can use template ID (mirxh0st37zf6iiw4zkt) or template name (vibe-code-fotz) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-code-fotz") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-code-fotz") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-code-fotz')

start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-code-fotz"
template_id = "mirxh0st37zf6iiw4zkt"
